source 'https://rubygems.org'

gem 'rails', '~> 5.2.0'
gem 'mysql2', '0.5.1'
gem 'devise'
gem 'devise-security', github: 'devise-security/devise-security'
gem 'newrelic_rpm'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails', '4.6.0'
gem 'jquery-ui-rails'
gem 'jbuilder'
gem 'best_in_place', '~> 3.0.1'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'activeadmin', '~> 2.0'
gem 'jquery-datatables-rails'
gem 'paperclip'
# gem 'active_admin_datetimepicker'
gem 'active_admin_theme'
gem 'active_admin_sidebar', git: 'https://github.com/activeadmin-plugins/active_admin_sidebar.git'
# gem 'responsive_active_admin'
gem 'arctic_admin'
gem "exception_notification"
gem 'state_machines'
gem 'state_machines-activerecord'
gem "select2-rails", '4.0.13'
gem 'config'
gem 'cancancan', '~> 1.10'
gem 'googleauth'
gem 'google-api-client', require: 'google/apis/analyticsreporting_v4'
gem 'activerecord-session_store'
gem 'active_model_otp'
gem 'piplapis-ruby'
gem "non-stupid-digest-assets"
gem 'validates_timeliness', '~> 4.0'
gem 'finance'
gem 'number_to_indian_currency'
gem 'geocoder'
gem 'data-confirm-modal', github: 'ifad/data-confirm-modal'
gem 'paper_trail'
gem 'paper_trail-association_tracking'
gem 'tinymce-rails'
gem 'activerecord-import'
gem 'xirr'
gem 'delayed_job_active_record'
gem "daemons"
gem 'google-analytics-rails', '1.1.0'
gem 'prawn'
gem 'prawn-rails'
gem 'rupees'
gem 'chronic', '~> 0.10.2'
gem 'gmaps4rails'
gem 'rest-client'
gem 'paper_trail-globalid'
gem 'text', '~> 1.3', '>= 1.3.1'
gem 'jaro_winkler'
gem "cocoon"
gem 'rubyzip', '~> 1.1.0'
gem 'axlsx', '2.1.0.pre'
gem 'axlsx_rails'
# gem 'gridhook'
gem 'multipart-post'
# gem 'emailhunter'
gem 'faye'
gem 'thin'
# gem 'sitemap_generator'
gem 'roo'
gem 'roo-xls'
gem 'deep_cloneable', '~> 2.3.0'
gem "chartkick", '1.5.2'
gem 'dalli'
gem 'rmagick', '4.2.6'
gem 'geoip2'
gem 'savon'
gem 'xlsxtream'
gem 'razorpay'
gem 'amazon-ecs'
gem 'ancestry'
# gem 'activeadmin_ancestry_view'
gem 'wicked'
gem 'aws-sdk', '~> 1.67.0'
gem 'aws-sdk-s3'
gem 'remotipart', '~> 1.2', '>= 1.2.1'
gem 'shortener'
# gem 'active_admin_import', '~> 2.1', '>= 2.1.2'
# gem 'activeadmin_reorderable'
gem 'acts_as_list'
gem 'friendly_id', '~> 5.2.4'
# gem 'activeadmin_quill_editor'
gem 'httpclient', '~> 2.8.2.4'
gem 'net-sftp'
gem 'net-ssh', '~> 5.2.0'
# gem 'activeadmin_addons'
gem 'puma', '~> 3.11.4'
gem 'ed25519'
gem 'rails-i18n'
gem 'bcrypt_pbkdf'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'puma_worker_killer'
gem 'spreadsheet'
gem 'rack-cors'
gem 'mini_magick'
gem 'combine_pdf'
gem 'pdf-reader', '~> 2.11'
gem 'active_model_serializers'
gem 'will_paginate', '~> 3.0'
gem "activeadmin-orderable"
gem 'activeadmin-searchable_select'
gem 'chunky_png', '~> 1.3', '>= 1.3.5'
gem 'nokogiri', '1.8.5'
gem 'loofah', '2.2.3'
gem 'sassc', '2.1.0'
gem 'turbolinks', '~> 5.1'
gem 'image_processing'

group :production, :test do
  gem 'secure_headers'
end

group :development, :test do
  gem 'traceroute'
  gem 'bullet'
  gem 'brakeman', :require => false
  gem 'rubocop', require: false
  gem "rubycritic", :require => false
  gem 'bootsnap', '>= 1.1.0', require: false
end

group :development do
  # gem 'quiet_assets'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rb-readline'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-rvm'
  gem 'capistrano3-delayed-job', '~> 1.0'
  gem 'capistrano-sidekiq'
  gem 'capistrano3-puma'
  gem 'pry'
  gem 'byebug'
end

gem 'pdftoimage'
gem 'jose', '~> 1.1', '>= 1.1.3'
gem 'terser'
# gem 'pandas'
gem 'rubyXL'
